services:
  api:
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: social-sentiment/backend:1
    container_name: social-sentiment-backend

    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      # - DATABASE_URL=postgres://user:password@postgres:5432/db
      # - MINIO_ENDPOINT=minio1
      # - MINIO_PORT=9000
      # - MINIO_USE_SSL=false
      # - MINIO_ACCESS_KEY=admin
      # - MINIO_SECRET_KEY=12345678
    # volumes:
    #   - ${HOST_VOLUME}:/usr/src/app
      # - /usr/src/app/node_modules
    command: npm run start:dev
    # networks:
    #   - external-network

# networks:
#   external-network:
#     external: true
